on:
  pull_request:
    branches:
      - main

jobs:
  Continuous_Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
      # Lint
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run ci:lint
      # Test
      # Build
